// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WebsocketPacket.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoBuf.WebSocketPacket {

  /// <summary>Holder for reflection information generated from WebsocketPacket.proto</summary>
  public static partial class WebsocketPacketReflection {

    #region Descriptor
    /// <summary>File descriptor for WebsocketPacket.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WebsocketPacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVXZWJzb2NrZXRQYWNrZXQucHJvdG8izAEKDFBheWxvYWRDbGFzcxIOCgZk",
            "ZXZpY2UYASABKAkSFwoPYXBwbGljYXRpb25OYW1lGAIgASgJEhoKEmFwcGxp",
            "Y2F0aW9uVmVyc2lvbhgDIAEoCRIQCgh1c2VyVVVJRBgEIAEoCRIWCg5icm9h",
            "ZENhc3RHcm91cBgFIAEoCRIhCgtyZXF1ZXN0Q29kZRgGIAEoDjIMLlBheWxv",
            "YWRUeXBlEhMKC3JlcXVlc3REYXRhGAcgASgMEhUKDXJlc3VsdE1lc3NhZ2UY",
            "CCABKAkiJgoUUGF5bG9hZENsYXNzVGVzdEVudW0SDgoGdXNlcklkGAEgASgJ",
            "KiYKC1BheWxvYWRUeXBlEggKBEluaXQQABINCghUZXN0RW51bRDoB0I1WhhQ",
            "cm90b0J1Zi9XZWJTb2NrZXRQYWNrZXSqAhhQcm90b0J1Zi5XZWJTb2NrZXRQ",
            "YWNrZXRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoBuf.WebSocketPacket.PayloadType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBuf.WebSocketPacket.PayloadClass), global::ProtoBuf.WebSocketPacket.PayloadClass.Parser, new[]{ "Device", "ApplicationName", "ApplicationVersion", "UserUUID", "BroadCastGroup", "RequestCode", "RequestData", "ResultMessage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBuf.WebSocketPacket.PayloadClassTestEnum), global::ProtoBuf.WebSocketPacket.PayloadClassTestEnum.Parser, new[]{ "UserId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PayloadType {
    [pbr::OriginalName("Init")] Init = 0,
    [pbr::OriginalName("TestEnum")] TestEnum = 1000,
  }

  #endregion

  #region Messages
  /// <summary>
  /// PayloadClass 메시지 정의
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayloadClass : pb::IMessage<PayloadClass>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayloadClass> _parser = new pb::MessageParser<PayloadClass>(() => new PayloadClass());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayloadClass> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBuf.WebSocketPacket.WebsocketPacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClass() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClass(PayloadClass other) : this() {
      device_ = other.device_;
      applicationName_ = other.applicationName_;
      applicationVersion_ = other.applicationVersion_;
      userUUID_ = other.userUUID_;
      broadCastGroup_ = other.broadCastGroup_;
      requestCode_ = other.requestCode_;
      requestData_ = other.requestData_;
      resultMessage_ = other.resultMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClass Clone() {
      return new PayloadClass(this);
    }

    /// <summary>Field number for the "device" field.</summary>
    public const int DeviceFieldNumber = 1;
    private string device_ = "";
    /// <summary>
    /// 1. 접속 디바이스 정보
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Device {
      get { return device_; }
      set {
        device_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "applicationName" field.</summary>
    public const int ApplicationNameFieldNumber = 2;
    private string applicationName_ = "";
    /// <summary>
    /// 2. 애플리케이션 이름
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApplicationName {
      get { return applicationName_; }
      set {
        applicationName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "applicationVersion" field.</summary>
    public const int ApplicationVersionFieldNumber = 3;
    private string applicationVersion_ = "";
    /// <summary>
    /// 3. 애플리케이션 버전
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApplicationVersion {
      get { return applicationVersion_; }
      set {
        applicationVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userUUID" field.</summary>
    public const int UserUUIDFieldNumber = 4;
    private string userUUID_ = "";
    /// <summary>
    /// 4. 사용자 UUID // 로그인 전이면 0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserUUID {
      get { return userUUID_; }
      set {
        userUUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "broadCastGroup" field.</summary>
    public const int BroadCastGroupFieldNumber = 5;
    private string broadCastGroup_ = "";
    /// <summary>
    /// 5. 방송 그룹 // 그룹이 없다면 0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BroadCastGroup {
      get { return broadCastGroup_; }
      set {
        broadCastGroup_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "requestCode" field.</summary>
    public const int RequestCodeFieldNumber = 6;
    private global::ProtoBuf.WebSocketPacket.PayloadType requestCode_ = global::ProtoBuf.WebSocketPacket.PayloadType.Init;
    /// <summary>
    /// 6. 요청 코드
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoBuf.WebSocketPacket.PayloadType RequestCode {
      get { return requestCode_; }
      set {
        requestCode_ = value;
      }
    }

    /// <summary>Field number for the "requestData" field.</summary>
    public const int RequestDataFieldNumber = 7;
    private pb::ByteString requestData_ = pb::ByteString.Empty;
    /// <summary>
    /// 7. 요청 데이터 (바이트 배열)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString RequestData {
      get { return requestData_; }
      set {
        requestData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resultMessage" field.</summary>
    public const int ResultMessageFieldNumber = 8;
    private string resultMessage_ = "";
    /// <summary>
    /// 8. 결과 메세지
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResultMessage {
      get { return resultMessage_; }
      set {
        resultMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayloadClass);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayloadClass other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Device != other.Device) return false;
      if (ApplicationName != other.ApplicationName) return false;
      if (ApplicationVersion != other.ApplicationVersion) return false;
      if (UserUUID != other.UserUUID) return false;
      if (BroadCastGroup != other.BroadCastGroup) return false;
      if (RequestCode != other.RequestCode) return false;
      if (RequestData != other.RequestData) return false;
      if (ResultMessage != other.ResultMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Device.Length != 0) hash ^= Device.GetHashCode();
      if (ApplicationName.Length != 0) hash ^= ApplicationName.GetHashCode();
      if (ApplicationVersion.Length != 0) hash ^= ApplicationVersion.GetHashCode();
      if (UserUUID.Length != 0) hash ^= UserUUID.GetHashCode();
      if (BroadCastGroup.Length != 0) hash ^= BroadCastGroup.GetHashCode();
      if (RequestCode != global::ProtoBuf.WebSocketPacket.PayloadType.Init) hash ^= RequestCode.GetHashCode();
      if (RequestData.Length != 0) hash ^= RequestData.GetHashCode();
      if (ResultMessage.Length != 0) hash ^= ResultMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Device.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Device);
      }
      if (ApplicationName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ApplicationName);
      }
      if (ApplicationVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ApplicationVersion);
      }
      if (UserUUID.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UserUUID);
      }
      if (BroadCastGroup.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BroadCastGroup);
      }
      if (RequestCode != global::ProtoBuf.WebSocketPacket.PayloadType.Init) {
        output.WriteRawTag(48);
        output.WriteEnum((int) RequestCode);
      }
      if (RequestData.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(RequestData);
      }
      if (ResultMessage.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ResultMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Device.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Device);
      }
      if (ApplicationName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ApplicationName);
      }
      if (ApplicationVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ApplicationVersion);
      }
      if (UserUUID.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UserUUID);
      }
      if (BroadCastGroup.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BroadCastGroup);
      }
      if (RequestCode != global::ProtoBuf.WebSocketPacket.PayloadType.Init) {
        output.WriteRawTag(48);
        output.WriteEnum((int) RequestCode);
      }
      if (RequestData.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(RequestData);
      }
      if (ResultMessage.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ResultMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Device.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Device);
      }
      if (ApplicationName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApplicationName);
      }
      if (ApplicationVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApplicationVersion);
      }
      if (UserUUID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserUUID);
      }
      if (BroadCastGroup.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BroadCastGroup);
      }
      if (RequestCode != global::ProtoBuf.WebSocketPacket.PayloadType.Init) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestCode);
      }
      if (RequestData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RequestData);
      }
      if (ResultMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResultMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayloadClass other) {
      if (other == null) {
        return;
      }
      if (other.Device.Length != 0) {
        Device = other.Device;
      }
      if (other.ApplicationName.Length != 0) {
        ApplicationName = other.ApplicationName;
      }
      if (other.ApplicationVersion.Length != 0) {
        ApplicationVersion = other.ApplicationVersion;
      }
      if (other.UserUUID.Length != 0) {
        UserUUID = other.UserUUID;
      }
      if (other.BroadCastGroup.Length != 0) {
        BroadCastGroup = other.BroadCastGroup;
      }
      if (other.RequestCode != global::ProtoBuf.WebSocketPacket.PayloadType.Init) {
        RequestCode = other.RequestCode;
      }
      if (other.RequestData.Length != 0) {
        RequestData = other.RequestData;
      }
      if (other.ResultMessage.Length != 0) {
        ResultMessage = other.ResultMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Device = input.ReadString();
            break;
          }
          case 18: {
            ApplicationName = input.ReadString();
            break;
          }
          case 26: {
            ApplicationVersion = input.ReadString();
            break;
          }
          case 34: {
            UserUUID = input.ReadString();
            break;
          }
          case 42: {
            BroadCastGroup = input.ReadString();
            break;
          }
          case 48: {
            RequestCode = (global::ProtoBuf.WebSocketPacket.PayloadType) input.ReadEnum();
            break;
          }
          case 58: {
            RequestData = input.ReadBytes();
            break;
          }
          case 66: {
            ResultMessage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Device = input.ReadString();
            break;
          }
          case 18: {
            ApplicationName = input.ReadString();
            break;
          }
          case 26: {
            ApplicationVersion = input.ReadString();
            break;
          }
          case 34: {
            UserUUID = input.ReadString();
            break;
          }
          case 42: {
            BroadCastGroup = input.ReadString();
            break;
          }
          case 48: {
            RequestCode = (global::ProtoBuf.WebSocketPacket.PayloadType) input.ReadEnum();
            break;
          }
          case 58: {
            RequestData = input.ReadBytes();
            break;
          }
          case 66: {
            ResultMessage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// TestEnum 메시지 정의 (1000)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PayloadClassTestEnum : pb::IMessage<PayloadClassTestEnum>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PayloadClassTestEnum> _parser = new pb::MessageParser<PayloadClassTestEnum>(() => new PayloadClassTestEnum());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PayloadClassTestEnum> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoBuf.WebSocketPacket.WebsocketPacketReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassTestEnum() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassTestEnum(PayloadClassTestEnum other) : this() {
      userId_ = other.userId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadClassTestEnum Clone() {
      return new PayloadClassTestEnum(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PayloadClassTestEnum);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PayloadClassTestEnum other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PayloadClassTestEnum other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
