// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.26.0--rc1
// source: WebsocketPacket.proto

package WebSocketPacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadType int32

const (
	PayloadType_Init     PayloadType = 0
	PayloadType_TestEnum PayloadType = 1000
)

// Enum value maps for PayloadType.
var (
	PayloadType_name = map[int32]string{
		0:    "Init",
		1000: "TestEnum",
	}
	PayloadType_value = map[string]int32{
		"Init":     0,
		"TestEnum": 1000,
	}
)

func (x PayloadType) Enum() *PayloadType {
	p := new(PayloadType)
	*p = x
	return p
}

func (x PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_WebsocketPacket_proto_enumTypes[0].Descriptor()
}

func (PayloadType) Type() protoreflect.EnumType {
	return &file_WebsocketPacket_proto_enumTypes[0]
}

func (x PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadType.Descriptor instead.
func (PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_WebsocketPacket_proto_rawDescGZIP(), []int{0}
}

// PayloadClass 메시지 정의
type PayloadClass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device             string      `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`                             // 1. 접속 디바이스 정보
	ApplicationName    string      `protobuf:"bytes,2,opt,name=applicationName,proto3" json:"applicationName,omitempty"`           // 2. 애플리케이션 이름
	ApplicationVersion string      `protobuf:"bytes,3,opt,name=applicationVersion,proto3" json:"applicationVersion,omitempty"`     // 3. 애플리케이션 버전
	UserUUID           string      `protobuf:"bytes,4,opt,name=userUUID,proto3" json:"userUUID,omitempty"`                         // 4. 사용자 UUID // 로그인 전이면 0
	BroadCastGroup     string      `protobuf:"bytes,5,opt,name=broadCastGroup,proto3" json:"broadCastGroup,omitempty"`             // 5. 방송 그룹 // 그룹이 없다면 0
	RequestCode        PayloadType `protobuf:"varint,6,opt,name=requestCode,proto3,enum=PayloadType" json:"requestCode,omitempty"` // 6. 요청 코드
	RequestData        []byte      `protobuf:"bytes,7,opt,name=requestData,proto3" json:"requestData,omitempty"`                   // 7. 요청 데이터 (바이트 배열)
	ResultMessage      string      `protobuf:"bytes,8,opt,name=resultMessage,proto3" json:"resultMessage,omitempty"`               // 8. 결과 메세지
}

func (x *PayloadClass) Reset() {
	*x = PayloadClass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WebsocketPacket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadClass) ProtoMessage() {}

func (x *PayloadClass) ProtoReflect() protoreflect.Message {
	mi := &file_WebsocketPacket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadClass.ProtoReflect.Descriptor instead.
func (*PayloadClass) Descriptor() ([]byte, []int) {
	return file_WebsocketPacket_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadClass) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *PayloadClass) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *PayloadClass) GetApplicationVersion() string {
	if x != nil {
		return x.ApplicationVersion
	}
	return ""
}

func (x *PayloadClass) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *PayloadClass) GetBroadCastGroup() string {
	if x != nil {
		return x.BroadCastGroup
	}
	return ""
}

func (x *PayloadClass) GetRequestCode() PayloadType {
	if x != nil {
		return x.RequestCode
	}
	return PayloadType_Init
}

func (x *PayloadClass) GetRequestData() []byte {
	if x != nil {
		return x.RequestData
	}
	return nil
}

func (x *PayloadClass) GetResultMessage() string {
	if x != nil {
		return x.ResultMessage
	}
	return ""
}

// TestEnum 메시지 정의 (1000)
type PayloadClassTestEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *PayloadClassTestEnum) Reset() {
	*x = PayloadClassTestEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WebsocketPacket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadClassTestEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadClassTestEnum) ProtoMessage() {}

func (x *PayloadClassTestEnum) ProtoReflect() protoreflect.Message {
	mi := &file_WebsocketPacket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadClassTestEnum.ProtoReflect.Descriptor instead.
func (*PayloadClassTestEnum) Descriptor() ([]byte, []int) {
	return file_WebsocketPacket_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadClassTestEnum) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_WebsocketPacket_proto protoreflect.FileDescriptor

var file_WebsocketPacket_proto_rawDesc = []byte{
	0x0a, 0x15, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x02, 0x0a, 0x0c, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x55, 0x55, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x43,
	0x61, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x62, 0x72, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x2e,
	0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x14, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x54, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x2a, 0x26, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x10, 0xe8, 0x07, 0x42, 0x35,
	0x5a, 0x18, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x75, 0x66, 0x2f, 0x57, 0x65, 0x62, 0x53, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0xaa, 0x02, 0x18, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x42, 0x75, 0x66, 0x2e, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_WebsocketPacket_proto_rawDescOnce sync.Once
	file_WebsocketPacket_proto_rawDescData = file_WebsocketPacket_proto_rawDesc
)

func file_WebsocketPacket_proto_rawDescGZIP() []byte {
	file_WebsocketPacket_proto_rawDescOnce.Do(func() {
		file_WebsocketPacket_proto_rawDescData = protoimpl.X.CompressGZIP(file_WebsocketPacket_proto_rawDescData)
	})
	return file_WebsocketPacket_proto_rawDescData
}

var file_WebsocketPacket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_WebsocketPacket_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_WebsocketPacket_proto_goTypes = []interface{}{
	(PayloadType)(0),             // 0: PayloadType
	(*PayloadClass)(nil),         // 1: PayloadClass
	(*PayloadClassTestEnum)(nil), // 2: PayloadClassTestEnum
}
var file_WebsocketPacket_proto_depIdxs = []int32{
	0, // 0: PayloadClass.requestCode:type_name -> PayloadType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_WebsocketPacket_proto_init() }
func file_WebsocketPacket_proto_init() {
	if File_WebsocketPacket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_WebsocketPacket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadClass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_WebsocketPacket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadClassTestEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WebsocketPacket_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WebsocketPacket_proto_goTypes,
		DependencyIndexes: file_WebsocketPacket_proto_depIdxs,
		EnumInfos:         file_WebsocketPacket_proto_enumTypes,
		MessageInfos:      file_WebsocketPacket_proto_msgTypes,
	}.Build()
	File_WebsocketPacket_proto = out.File
	file_WebsocketPacket_proto_rawDesc = nil
	file_WebsocketPacket_proto_goTypes = nil
	file_WebsocketPacket_proto_depIdxs = nil
}
